function letter = num2letter(num)
    switch(num)
        case 1, letter = 'a';
        case 2, letter = 'b';
        case 3, letter = 'c';
        case 4, letter = 'd';
        case 5, letter = 'e';
        case 6, letter = 'f';
        case 7, letter = 'g';
        case 8, letter = 'h';
        case 9, letter = 'i';
        case 10, letter = 'j';
        case 11, letter = 'k';
        case 12, letter = 'l';
        case 13, letter = 'm';
        case 14, letter = 'n';
        case 15, letter = 'o';
        case 16, letter = 'p';
        case 17, letter = 'q';
        case 18, letter = 'r';
        case 19, letter = 's';
        case 20, letter = 't';
        case 21, letter = 'u';
        case 22, letter = 'v';
        case 23, letter = 'w';
        case 24, letter = 'x';
        case 25, letter = 'y';
        case 26, letter = 'z';
        otherwise, letter = '*';
end